<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8BiFXDk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8BiFXDk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8BiFXDk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8BiFXDk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8BiFXDk\App_KernelDevDebugContainer([
    'container.build_hash' => '8BiFXDk',
    'container.build_id' => 'ee2f6556',
    'container.build_time' => 1722316878,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8BiFXDk');
